on: push
name: Tests
jobs:
  node:
    strategy:
      matrix:
        node: ["17", 16", "14", "12"]
    name: Node.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - run: npm install
      - run: npm test
  php:
    strategy:
      matrix:
        # https://www.php.net/supported-versions.php
        php: ["7.3", "7.4", "8.0"]
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          tools: phpunit, composer
      - run: composer install --no-interaction
      - run: phpunit -d memory_limit=-1
  ruby:
    strategy:
      matrix:
        ruby: ["3.0", "2.6", "2.7"]
    name: Ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rake
  go:
    strategy:
      matrix:
        go: ["^1.16.10", "^1.17.3"]
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          bundler-cache: true
      - run: make go-test
